
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_todo_management
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql

messages:
  exceptions:
    todo:
      not-found: "Todo not found, with id: "
  controllers:
    todo:
      deleted-success: "Todo deleted successfully, with id: "